### ISSUE TITLE
IsPS4OrPS5Platform() compile error - doesn't exist

### ISSUE THREAD

**Issue by DigiMaxIO** [djsmax/Subnautica-macOS-fixes#2]
Your missing some instructions for the gamepad fix, the original file has ".PS4" and ".PS5" for naming the gamepads but your c# code has function IsPS4OrPS5Platform(), which generates a compiler error stating that it doesn't exist.

**Edit:** Turns out this issue only pertains to Subnautica the original. Subnautica: Below Zero does in fact have this function.
Didn't try to see if adding this to the original would work or not, but _here's the code to add that in function:_
	// Token: 0x06002623 RID: 9763 RVA: 0x0000466A File Offset: 0x0000286A
	.method private hidebysig static 
		bool IsPS4OrPS5Platform () cil managed 
	{
		// Header Size: 1 byte
		// Code Size: 2 (0x2) bytes
		.maxstack 8

		/* 0x0000286B 16           */ IL_0000: ldc.i4.0
		/* 0x0000286C 2A           */ IL_0001: ret
	} // end of method GameInput::IsPS4OrPS5Platform

_An alternative fix is this:_
if (controllerLayout == GameInput.ControllerLayout.Xbox360 || controllerLayout == GameInput.ControllerLayout.XboxOne || GameInput.ControllerLayout.PS4 || GameInput.ControllerLayout.PS5 || controllerLayout == GameInput.ControllerLayout.Scarlett)
{

**Comment by x-0D** [comment]
Working patches can be found here: https://github.com/djsmax/Subnautica-macOS-fixes/pull/3

**Comment by djsmax** [comment]
Were you able to patch it in the end? Sorry I didn't see your first issue, oops..

**Comment by DigiMaxIO** [comment]
@djsmax , yes I was able to install the patch on both games! Apologies I forgot to close that issue. I didn't think it was working at first because I was using a PS5 controller. Didn't matter whether the PS5 controller was on bluetooth or USB, _the PS5 controller mappings aren't correct_ so they don't work, I'd assume PS4 controllers are the same. However, _Xbox one controllers work perfectly through bluetooth_.

Can't thank you enough for this patch, always drove me mental that the devs never fixed this issue, Subnautica is such a perfect game series for the MacOS system, it's a shame they didn't fix something as simple as that.

**Additional Installation Notes:** 

**1.** The assembly code instructions imply that you can just copy the text from the IL files and paste it into the "Edit IL Instructions" window, but I was unable to figure out how to paste it in (the software grayed out the paste command in that window), so ended up doing the C# method. 

**2.** It might be worth adding to the instructions that you need to go File->Save Module... once you've made the changes for them to go through.
